# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main
  - release-*

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: SonarCloudPrepare@1
      displayName: 'Prepare SonarCloud analysis configuration'
      inputs:
        SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
        organization: '$(SONARCLOUD_ORG)'
        scannerMode: Other
        extraProperties: |
          sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
          sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        options: '-B -DskipTests=true'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: true
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        sonarQubeRunAnalysis: false
    - task: SonarCloudPublish@1
      displayName: 'Publish SonarCloud results on build summary'
      inputs:
        pollingTimeoutSec: '300'