package it.pagopa.pdv.tokenizer.connector.dao.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.Map;

@Data
@DynamoDBTable(tableName = "people")
public class Person {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "gsi_fiscal_code")
    private String fiscalCode;

    @DynamoDBAttribute
    private String givenName;

    @DynamoDBAttribute
    private String familyName;

    @DynamoDBAttribute
    private Map<String, WorkContact> workContacts;


    @Data
    @DynamoDBDocument
    public static class WorkContact {

        @DynamoDBAttribute
        private String email;

    }

}
